#!/usr/bin/env python

from ast import literal_eval
import sys
from argparse import ArgumentParser
from subprocess import Popen, PIPE


def time_string_to_seconds(rawdur):
    rawdur = rawdur.strip(",")
    rawdur, _, milli = rawdur.rpartition(".")
    milli = int(milli)
    rawdur, _, sec = rawdur.rpartition(":")
    sec = int(sec)
    rawdur, _, mins = rawdur.rpartition(":")
    mins = int(mins)
    hours = int(rawdur)
    return (3600 * hours + 60 * mins + sec + (milli / 1000))


def get_track_length(track_num, chapter=None):
    cmd = ["lsdvd", "-t", str(track_num), "-Oy"]
    if chapter is not None:
        cmd.append("-c")
    p = Popen(cmd, stdout=PIPE)
    stdout, stderr = p.communicate()
    lsdvd = literal_eval(stdout[8:])
    trackdict = [t for t in lsdvd["track"] if t["ix"] == track_num][0]
    if chapter is not None:
        chapterdict = [c for c in trackdict["chapter"] if c["ix"] == chapter][0]
        return chapterdict["length"]
    return trackdict["length"]


def get_file_length(eachfile):
    cmd = ["ffmpeg", "-i", eachfile]
    p = Popen(cmd, stderr=PIPE)
    stdout, stderr = p.communicate()
    for line in stderr.split("\n"):
        if "Duration" in line:
            break
    else:
        raise RuntimeError
    line = line.strip()
    rawdur = line.split()[1]
    rawdur = rawdur.rstrip(",")
    return time_string_to_seconds(rawdur)


def parse_arguments():
    parser = ArgumentParser()
    parser.add_argument("--file", help="The file to check the duration of",
                        required=True)
    parser.add_argument("--track", help="The DVD track number to check the "
                        "duration of", type=int, required=True)
    parser.add_argument("--chapter", help="The DVD chapter number to check",
                        type=int)
    return parser.parse_args()


def main():
    args = parse_arguments()
    track_length = get_track_length(args.track, chapter=args.chapter)
    file_length = get_file_length(args.file)
    print("track: %ss vs file: %ss" % (track_length, file_length))
    if abs(track_length - file_length) <= 5:
        return True
    return False

if __name__ == "__main__":
    if main() is True:
        sys.exit(0)
    sys.exit(1)
