#!/usr/bin/env python

import sys
from argparse import ArgumentParser
from rip import check_length


def parse_arguments():
    parser = ArgumentParser()
    parser.add_argument("--file", help="The file to check the duration of",
                        required=True)
    parser.add_argument("--track", help="The DVD track number to check the "
                        "duration of", type=int, required=True)
    parser.add_argument("--chapter", help="The DVD chapter number to check",
                        type=int)
    return parser.parse_args()


def main():
    args = parse_arguments()
    return check_length(args.file, args.track, args.chapter)

if __name__ == "__main__":
    if main() is True:
        sys.exit(0)
    sys.exit(1)
