#!/usr/bin/env python
from argparse import ArgumentParser
from rip import rip_track, get_subtitle_flags
from os.path import splitext


def parse_args():
    parser = ArgumentParser()
    parser.add_argument("inputfile")
    parser.add_argument("filename", nargs="?")
    parser.add_argument("--animation", action="store_true")
    parser.add_argument("--decomb", action="store_true")
    parser.add_argument("--deinterlace", action="store_true")
    return parser.parse_args()


def main():
    args = parse_args()

    if args.filename is None:
        inputnoext, ext = splitext(args.inputfile)
        filename = "%s.%s" % (inputnoext.rstrip("."), "m4v")
    else:
        filename = args.filename
    rip_track(filename, inputfile=args.inputfile,
              animation=args.animation, decomb=args.decomb,
              deinterlace=args.deinterlace, subtitleflags=get_subtitle_flags())

if __name__ == "__main__":
    main()
