#!/usr/bin/env python
from argparse import ArgumentParser
from rip import rip_track, add_handbrake_flags, get_handbrake_flags
from os.path import splitext


def parse_args():
    parser = ArgumentParser()
    parser.add_argument("inputfile")
    parser.add_argument("filename", nargs="?")
    parser = add_handbrake_flags(parser)
    return parser.parse_args()


def main():
    args = parse_args()

    if args.filename is None:
        inputnoext, ext = splitext(args.inputfile)
        filename = "%s.%s" % (inputnoext.rstrip("."), "m4v")
    else:
        filename = args.filename
    hbflags = get_handbrake_flags(args)

    rip_track(filename, inputfile=args.inputfile, handbrake_flags=hbflags)

if __name__ == "__main__":
    main()
